/*
 * generated by Xtext
 */
package DAGx;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import DAGx.scoping.DAGxNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DAGxRuntimeModule extends DAGx.AbstractDAGxRuntimeModule {
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		// TODO Auto-generated method stub
		return DAGxNameProvider.class;
	}

}
