/*
* generated by Xtext
*/
package DAGx;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DAGxStandaloneSetup extends DAGxStandaloneSetupGenerated{

	public static void doSetup() {
		new DAGxStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

